### ISSUE TITLE
README/documentation

### ISSUE THREAD

**Issue by AlexMalfr** [jzarca01/node-homiris#1]
Bonjour,
Ce serait possible d'avoir un petit README et/ou des commentaires dans le code pour savoir ce sont est capable cette lib et comment l'utiliser ? 🙂
Ce serait pour éventuellement l'intégrer dans Home Assistant

**Comment by jzarca01** [comment]
Bonjour, tu peux utiliser https://github.com/jzarca01/docker-homiris et mqtt pour integrer homiris à home assistant
